//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("FlightsModel", "FK_Flight_Aircraft", "Aircraft", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Flights_Service.Aircraft), "Flight", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Flights_Service.Flight), true)]
[assembly: EdmRelationshipAttribute("FlightsModel", "FK_Flight_Airline", "Airline", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Flights_Service.Airline), "Flight", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Flights_Service.Flight), true)]
[assembly: EdmRelationshipAttribute("FlightsModel", "Flights2Airports", "AirportInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Flights_Service.AirportInfo), "Flight", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Flights_Service.Flight))]
[assembly: EdmRelationshipAttribute("FlightsModel", "Flights2Members", "Flight", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Flights_Service.Flight), "Member", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Flights_Service.Member))]

#endregion

namespace Flights_Service
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class FlightsEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new FlightsEntities object using the connection string found in the 'FlightsEntities' section of the application configuration file.
        /// </summary>
        public FlightsEntities() : base("name=FlightsEntities", "FlightsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FlightsEntities object.
        /// </summary>
        public FlightsEntities(string connectionString) : base(connectionString, "FlightsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FlightsEntities object.
        /// </summary>
        public FlightsEntities(EntityConnection connection) : base(connection, "FlightsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Aircraft> Aircraft
        {
            get
            {
                if ((_Aircraft == null))
                {
                    _Aircraft = base.CreateObjectSet<Aircraft>("Aircraft");
                }
                return _Aircraft;
            }
        }
        private ObjectSet<Aircraft> _Aircraft;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Airline> Airlines
        {
            get
            {
                if ((_Airlines == null))
                {
                    _Airlines = base.CreateObjectSet<Airline>("Airlines");
                }
                return _Airlines;
            }
        }
        private ObjectSet<Airline> _Airlines;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AirportInfo> AirportInfoes
        {
            get
            {
                if ((_AirportInfoes == null))
                {
                    _AirportInfoes = base.CreateObjectSet<AirportInfo>("AirportInfoes");
                }
                return _AirportInfoes;
            }
        }
        private ObjectSet<AirportInfo> _AirportInfoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Flight> Flights
        {
            get
            {
                if ((_Flights == null))
                {
                    _Flights = base.CreateObjectSet<Flight>("Flights");
                }
                return _Flights;
            }
        }
        private ObjectSet<Flight> _Flights;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Member> Members
        {
            get
            {
                if ((_Members == null))
                {
                    _Members = base.CreateObjectSet<Member>("Members");
                }
                return _Members;
            }
        }
        private ObjectSet<Member> _Members;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Aircraft EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAircraft(Aircraft aircraft)
        {
            base.AddObject("Aircraft", aircraft);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Airlines EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAirlines(Airline airline)
        {
            base.AddObject("Airlines", airline);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AirportInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAirportInfoes(AirportInfo airportInfo)
        {
            base.AddObject("AirportInfoes", airportInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Flights EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFlights(Flight flight)
        {
            base.AddObject("Flights", flight);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Members EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMembers(Member member)
        {
            base.AddObject("Members", member);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FlightsModel", Name="Aircraft")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Aircraft : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Aircraft object.
        /// </summary>
        /// <param name="aircraftID">Initial value of the AircraftID property.</param>
        public static Aircraft CreateAircraft(global::System.Int32 aircraftID)
        {
            Aircraft aircraft = new Aircraft();
            aircraft.AircraftID = aircraftID;
            return aircraft;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AircraftID
        {
            get
            {
                return _AircraftID;
            }
            set
            {
                if (_AircraftID != value)
                {
                    OnAircraftIDChanging(value);
                    ReportPropertyChanging("AircraftID");
                    _AircraftID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AircraftID");
                    OnAircraftIDChanged();
                }
            }
        }
        private global::System.Int32 _AircraftID;
        partial void OnAircraftIDChanging(global::System.Int32 value);
        partial void OnAircraftIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FirstDate
        {
            get
            {
                return _FirstDate;
            }
            set
            {
                OnFirstDateChanging(value);
                ReportPropertyChanging("FirstDate");
                _FirstDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FirstDate");
                OnFirstDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _FirstDate;
        partial void OnFirstDateChanging(Nullable<global::System.DateTime> value);
        partial void OnFirstDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Length
        {
            get
            {
                return _Length;
            }
            set
            {
                OnLengthChanging(value);
                ReportPropertyChanging("Length");
                _Length = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Length");
                OnLengthChanged();
            }
        }
        private Nullable<global::System.Decimal> _Length;
        partial void OnLengthChanging(Nullable<global::System.Decimal> value);
        partial void OnLengthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Height
        {
            get
            {
                return _Height;
            }
            set
            {
                OnHeightChanging(value);
                ReportPropertyChanging("Height");
                _Height = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Height");
                OnHeightChanged();
            }
        }
        private Nullable<global::System.Decimal> _Height;
        partial void OnHeightChanging(Nullable<global::System.Decimal> value);
        partial void OnHeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Wingspan
        {
            get
            {
                return _Wingspan;
            }
            set
            {
                OnWingspanChanging(value);
                ReportPropertyChanging("Wingspan");
                _Wingspan = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Wingspan");
                OnWingspanChanged();
            }
        }
        private Nullable<global::System.Decimal> _Wingspan;
        partial void OnWingspanChanging(Nullable<global::System.Decimal> value);
        partial void OnWingspanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Diameter
        {
            get
            {
                return _Diameter;
            }
            set
            {
                OnDiameterChanging(value);
                ReportPropertyChanging("Diameter");
                _Diameter = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Diameter");
                OnDiameterChanged();
            }
        }
        private Nullable<global::System.Decimal> _Diameter;
        partial void OnDiameterChanging(Nullable<global::System.Decimal> value);
        partial void OnDiameterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Speed
        {
            get
            {
                return _Speed;
            }
            set
            {
                OnSpeedChanging(value);
                ReportPropertyChanging("Speed");
                _Speed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Speed");
                OnSpeedChanged();
            }
        }
        private Nullable<global::System.Decimal> _Speed;
        partial void OnSpeedChanging(Nullable<global::System.Decimal> value);
        partial void OnSpeedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Manufacturer
        {
            get
            {
                return _Manufacturer;
            }
            set
            {
                OnManufacturerChanging(value);
                ReportPropertyChanging("Manufacturer");
                _Manufacturer = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Manufacturer");
                OnManufacturerChanged();
            }
        }
        private global::System.String _Manufacturer;
        partial void OnManufacturerChanging(global::System.String value);
        partial void OnManufacturerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> Capacity
        {
            get
            {
                return _Capacity;
            }
            set
            {
                OnCapacityChanging(value);
                ReportPropertyChanging("Capacity");
                _Capacity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Capacity");
                OnCapacityChanged();
            }
        }
        private Nullable<global::System.Int16> _Capacity;
        partial void OnCapacityChanging(Nullable<global::System.Int16> value);
        partial void OnCapacityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> Engines
        {
            get
            {
                return _Engines;
            }
            set
            {
                OnEnginesChanging(value);
                ReportPropertyChanging("Engines");
                _Engines = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Engines");
                OnEnginesChanged();
            }
        }
        private Nullable<global::System.Byte> _Engines;
        partial void OnEnginesChanging(Nullable<global::System.Byte> value);
        partial void OnEnginesChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FlightsModel", "FK_Flight_Aircraft", "Flight")]
        public EntityCollection<Flight> Flights
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Flight>("FlightsModel.FK_Flight_Aircraft", "Flight");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Flight>("FlightsModel.FK_Flight_Aircraft", "Flight", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FlightsModel", Name="Airline")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Airline : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Airline object.
        /// </summary>
        /// <param name="airlineID">Initial value of the AirlineID property.</param>
        public static Airline CreateAirline(global::System.Int32 airlineID)
        {
            Airline airline = new Airline();
            airline.AirlineID = airlineID;
            return airline;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AirlineID
        {
            get
            {
                return _AirlineID;
            }
            set
            {
                if (_AirlineID != value)
                {
                    OnAirlineIDChanging(value);
                    ReportPropertyChanging("AirlineID");
                    _AirlineID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AirlineID");
                    OnAirlineIDChanged();
                }
            }
        }
        private global::System.Int32 _AirlineID;
        partial void OnAirlineIDChanging(global::System.Int32 value);
        partial void OnAirlineIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AirlineCountry
        {
            get
            {
                return _AirlineCountry;
            }
            set
            {
                OnAirlineCountryChanging(value);
                ReportPropertyChanging("AirlineCountry");
                _AirlineCountry = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AirlineCountry");
                OnAirlineCountryChanged();
            }
        }
        private global::System.String _AirlineCountry;
        partial void OnAirlineCountryChanging(global::System.String value);
        partial void OnAirlineCountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Website
        {
            get
            {
                return _Website;
            }
            set
            {
                OnWebsiteChanging(value);
                ReportPropertyChanging("Website");
                _Website = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Website");
                OnWebsiteChanged();
            }
        }
        private global::System.String _Website;
        partial void OnWebsiteChanging(global::System.String value);
        partial void OnWebsiteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> OnlineCheckIN
        {
            get
            {
                return _OnlineCheckIN;
            }
            set
            {
                OnOnlineCheckINChanging(value);
                ReportPropertyChanging("OnlineCheckIN");
                _OnlineCheckIN = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OnlineCheckIN");
                OnOnlineCheckINChanged();
            }
        }
        private Nullable<global::System.Boolean> _OnlineCheckIN;
        partial void OnOnlineCheckINChanging(Nullable<global::System.Boolean> value);
        partial void OnOnlineCheckINChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> HotelBooking
        {
            get
            {
                return _HotelBooking;
            }
            set
            {
                OnHotelBookingChanging(value);
                ReportPropertyChanging("HotelBooking");
                _HotelBooking = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HotelBooking");
                OnHotelBookingChanged();
            }
        }
        private Nullable<global::System.Boolean> _HotelBooking;
        partial void OnHotelBookingChanging(Nullable<global::System.Boolean> value);
        partial void OnHotelBookingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> CarRental
        {
            get
            {
                return _CarRental;
            }
            set
            {
                OnCarRentalChanging(value);
                ReportPropertyChanging("CarRental");
                _CarRental = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CarRental");
                OnCarRentalChanged();
            }
        }
        private Nullable<global::System.Boolean> _CarRental;
        partial void OnCarRentalChanging(Nullable<global::System.Boolean> value);
        partial void OnCarRentalChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FlightsModel", "FK_Flight_Airline", "Flight")]
        public EntityCollection<Flight> Flights
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Flight>("FlightsModel.FK_Flight_Airline", "Flight");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Flight>("FlightsModel.FK_Flight_Airline", "Flight", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FlightsModel", Name="AirportInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AirportInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AirportInfo object.
        /// </summary>
        /// <param name="airportID">Initial value of the AirportID property.</param>
        public static AirportInfo CreateAirportInfo(global::System.Int32 airportID)
        {
            AirportInfo airportInfo = new AirportInfo();
            airportInfo.AirportID = airportID;
            return airportInfo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AirportID
        {
            get
            {
                return _AirportID;
            }
            set
            {
                if (_AirportID != value)
                {
                    OnAirportIDChanging(value);
                    ReportPropertyChanging("AirportID");
                    _AirportID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AirportID");
                    OnAirportIDChanged();
                }
            }
        }
        private global::System.Int32 _AirportID;
        partial void OnAirportIDChanging(global::System.Int32 value);
        partial void OnAirportIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AirportPhone
        {
            get
            {
                return _AirportPhone;
            }
            set
            {
                OnAirportPhoneChanging(value);
                ReportPropertyChanging("AirportPhone");
                _AirportPhone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AirportPhone");
                OnAirportPhoneChanged();
            }
        }
        private global::System.String _AirportPhone;
        partial void OnAirportPhoneChanging(global::System.String value);
        partial void OnAirportPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Fax
        {
            get
            {
                return _Fax;
            }
            set
            {
                OnFaxChanging(value);
                ReportPropertyChanging("Fax");
                _Fax = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fax");
                OnFaxChanged();
            }
        }
        private Nullable<global::System.Boolean> _Fax;
        partial void OnFaxChanging(Nullable<global::System.Boolean> value);
        partial void OnFaxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Street
        {
            get
            {
                return _Street;
            }
            set
            {
                OnStreetChanging(value);
                ReportPropertyChanging("Street");
                _Street = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Street");
                OnStreetChanged();
            }
        }
        private global::System.String _Street;
        partial void OnStreetChanging(global::System.String value);
        partial void OnStreetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Postalcode
        {
            get
            {
                return _Postalcode;
            }
            set
            {
                OnPostalcodeChanging(value);
                ReportPropertyChanging("Postalcode");
                _Postalcode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Postalcode");
                OnPostalcodeChanged();
            }
        }
        private global::System.String _Postalcode;
        partial void OnPostalcodeChanging(global::System.String value);
        partial void OnPostalcodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AirportWebsite
        {
            get
            {
                return _AirportWebsite;
            }
            set
            {
                OnAirportWebsiteChanging(value);
                ReportPropertyChanging("AirportWebsite");
                _AirportWebsite = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AirportWebsite");
                OnAirportWebsiteChanged();
            }
        }
        private global::System.String _AirportWebsite;
        partial void OnAirportWebsiteChanging(global::System.String value);
        partial void OnAirportWebsiteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Airport
        {
            get
            {
                return _Airport;
            }
            set
            {
                OnAirportChanging(value);
                ReportPropertyChanging("Airport");
                _Airport = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Airport");
                OnAirportChanged();
            }
        }
        private global::System.String _Airport;
        partial void OnAirportChanging(global::System.String value);
        partial void OnAirportChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FlightsModel", "Flights2Airports", "Flight")]
        public EntityCollection<Flight> Flights
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Flight>("FlightsModel.Flights2Airports", "Flight");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Flight>("FlightsModel.Flights2Airports", "Flight", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FlightsModel", Name="Flight")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Flight : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Flight object.
        /// </summary>
        /// <param name="flightID">Initial value of the FlightID property.</param>
        public static Flight CreateFlight(global::System.Int32 flightID)
        {
            Flight flight = new Flight();
            flight.FlightID = flightID;
            return flight;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FlightID
        {
            get
            {
                return _FlightID;
            }
            set
            {
                if (_FlightID != value)
                {
                    OnFlightIDChanging(value);
                    ReportPropertyChanging("FlightID");
                    _FlightID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FlightID");
                    OnFlightIDChanged();
                }
            }
        }
        private global::System.Int32 _FlightID;
        partial void OnFlightIDChanging(global::System.Int32 value);
        partial void OnFlightIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.String _Date;
        partial void OnDateChanging(global::System.String value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FlightNumber
        {
            get
            {
                return _FlightNumber;
            }
            set
            {
                OnFlightNumberChanging(value);
                ReportPropertyChanging("FlightNumber");
                _FlightNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FlightNumber");
                OnFlightNumberChanged();
            }
        }
        private global::System.String _FlightNumber;
        partial void OnFlightNumberChanging(global::System.String value);
        partial void OnFlightNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DepTime
        {
            get
            {
                return _DepTime;
            }
            set
            {
                OnDepTimeChanging(value);
                ReportPropertyChanging("DepTime");
                _DepTime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DepTime");
                OnDepTimeChanged();
            }
        }
        private global::System.String _DepTime;
        partial void OnDepTimeChanging(global::System.String value);
        partial void OnDepTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ArrvTime
        {
            get
            {
                return _ArrvTime;
            }
            set
            {
                OnArrvTimeChanging(value);
                ReportPropertyChanging("ArrvTime");
                _ArrvTime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ArrvTime");
                OnArrvTimeChanged();
            }
        }
        private global::System.String _ArrvTime;
        partial void OnArrvTimeChanging(global::System.String value);
        partial void OnArrvTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GroundOp
        {
            get
            {
                return _GroundOp;
            }
            set
            {
                OnGroundOpChanging(value);
                ReportPropertyChanging("GroundOp");
                _GroundOp = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GroundOp");
                OnGroundOpChanged();
            }
        }
        private global::System.String _GroundOp;
        partial void OnGroundOpChanging(global::System.String value);
        partial void OnGroundOpChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AirlineID
        {
            get
            {
                return _AirlineID;
            }
            set
            {
                OnAirlineIDChanging(value);
                ReportPropertyChanging("AirlineID");
                _AirlineID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AirlineID");
                OnAirlineIDChanged();
            }
        }
        private Nullable<global::System.Int32> _AirlineID;
        partial void OnAirlineIDChanging(Nullable<global::System.Int32> value);
        partial void OnAirlineIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AircraftID
        {
            get
            {
                return _AircraftID;
            }
            set
            {
                OnAircraftIDChanging(value);
                ReportPropertyChanging("AircraftID");
                _AircraftID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AircraftID");
                OnAircraftIDChanged();
            }
        }
        private Nullable<global::System.Int32> _AircraftID;
        partial void OnAircraftIDChanging(Nullable<global::System.Int32> value);
        partial void OnAircraftIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FlightsModel", "FK_Flight_Aircraft", "Aircraft")]
        public Aircraft Aircraft
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Aircraft>("FlightsModel.FK_Flight_Aircraft", "Aircraft").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Aircraft>("FlightsModel.FK_Flight_Aircraft", "Aircraft").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Aircraft> AircraftReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Aircraft>("FlightsModel.FK_Flight_Aircraft", "Aircraft");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Aircraft>("FlightsModel.FK_Flight_Aircraft", "Aircraft", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FlightsModel", "FK_Flight_Airline", "Airline")]
        public Airline Airline
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Airline>("FlightsModel.FK_Flight_Airline", "Airline").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Airline>("FlightsModel.FK_Flight_Airline", "Airline").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Airline> AirlineReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Airline>("FlightsModel.FK_Flight_Airline", "Airline");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Airline>("FlightsModel.FK_Flight_Airline", "Airline", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FlightsModel", "Flights2Airports", "AirportInfo")]
        public EntityCollection<AirportInfo> AirportInfoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<AirportInfo>("FlightsModel.Flights2Airports", "AirportInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<AirportInfo>("FlightsModel.Flights2Airports", "AirportInfo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FlightsModel", "Flights2Members", "Member")]
        public EntityCollection<Member> Members
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Member>("FlightsModel.Flights2Members", "Member");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Member>("FlightsModel.Flights2Members", "Member", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FlightsModel", Name="Member")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Member : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Member object.
        /// </summary>
        /// <param name="memberID">Initial value of the MemberID property.</param>
        /// <param name="memberName">Initial value of the MemberName property.</param>
        /// <param name="position">Initial value of the Position property.</param>
        /// <param name="country">Initial value of the Country property.</param>
        /// <param name="age">Initial value of the Age property.</param>
        /// <param name="years">Initial value of the Years property.</param>
        public static Member CreateMember(global::System.Int32 memberID, global::System.String memberName, global::System.String position, global::System.String country, global::System.Int32 age, global::System.Int32 years)
        {
            Member member = new Member();
            member.MemberID = memberID;
            member.MemberName = memberName;
            member.Position = position;
            member.Country = country;
            member.Age = age;
            member.Years = years;
            return member;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MemberID
        {
            get
            {
                return _MemberID;
            }
            set
            {
                if (_MemberID != value)
                {
                    OnMemberIDChanging(value);
                    ReportPropertyChanging("MemberID");
                    _MemberID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MemberID");
                    OnMemberIDChanged();
                }
            }
        }
        private global::System.Int32 _MemberID;
        partial void OnMemberIDChanging(global::System.Int32 value);
        partial void OnMemberIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MemberName
        {
            get
            {
                return _MemberName;
            }
            set
            {
                OnMemberNameChanging(value);
                ReportPropertyChanging("MemberName");
                _MemberName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MemberName");
                OnMemberNameChanged();
            }
        }
        private global::System.String _MemberName;
        partial void OnMemberNameChanging(global::System.String value);
        partial void OnMemberNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Position
        {
            get
            {
                return _Position;
            }
            set
            {
                OnPositionChanging(value);
                ReportPropertyChanging("Position");
                _Position = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Position");
                OnPositionChanged();
            }
        }
        private global::System.String _Position;
        partial void OnPositionChanging(global::System.String value);
        partial void OnPositionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Country
        {
            get
            {
                return _Country;
            }
            set
            {
                OnCountryChanging(value);
                ReportPropertyChanging("Country");
                _Country = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Country");
                OnCountryChanged();
            }
        }
        private global::System.String _Country;
        partial void OnCountryChanging(global::System.String value);
        partial void OnCountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Age
        {
            get
            {
                return _Age;
            }
            set
            {
                OnAgeChanging(value);
                ReportPropertyChanging("Age");
                _Age = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Age");
                OnAgeChanged();
            }
        }
        private global::System.Int32 _Age;
        partial void OnAgeChanging(global::System.Int32 value);
        partial void OnAgeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Years
        {
            get
            {
                return _Years;
            }
            set
            {
                OnYearsChanging(value);
                ReportPropertyChanging("Years");
                _Years = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Years");
                OnYearsChanged();
            }
        }
        private global::System.Int32 _Years;
        partial void OnYearsChanging(global::System.Int32 value);
        partial void OnYearsChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FlightsModel", "Flights2Members", "Flight")]
        public EntityCollection<Flight> Flights
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Flight>("FlightsModel.Flights2Members", "Flight");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Flight>("FlightsModel.Flights2Members", "Flight", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FlightsModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }

    #endregion

    
}
