//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("FlightsModel", "FK_Flight_Aircraft", "Aircraft", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Flights_Service.Aircraft), "Flight", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Flights_Service.Flight), true)]
[assembly: EdmRelationshipAttribute("FlightsModel", "FK_Flight_Airline", "Airline", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Flights_Service.Airline), "Flight", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Flights_Service.Flight), true)]

#endregion

namespace Flights_Service
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class FlightsEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new FlightsEntities1 object using the connection string found in the 'FlightsEntities1' section of the application configuration file.
        /// </summary>
        public FlightsEntities1() : base("name=FlightsEntities1", "FlightsEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FlightsEntities1 object.
        /// </summary>
        public FlightsEntities1(string connectionString) : base(connectionString, "FlightsEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FlightsEntities1 object.
        /// </summary>
        public FlightsEntities1(EntityConnection connection) : base(connection, "FlightsEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Aircraft> Aircraft
        {
            get
            {
                if ((_Aircraft == null))
                {
                    _Aircraft = base.CreateObjectSet<Aircraft>("Aircraft");
                }
                return _Aircraft;
            }
        }
        private ObjectSet<Aircraft> _Aircraft;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Aircrew> Aircrews
        {
            get
            {
                if ((_Aircrews == null))
                {
                    _Aircrews = base.CreateObjectSet<Aircrew>("Aircrews");
                }
                return _Aircrews;
            }
        }
        private ObjectSet<Aircrew> _Aircrews;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Airline> Airlines
        {
            get
            {
                if ((_Airlines == null))
                {
                    _Airlines = base.CreateObjectSet<Airline>("Airlines");
                }
                return _Airlines;
            }
        }
        private ObjectSet<Airline> _Airlines;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AirportInfo> AirportInfoes
        {
            get
            {
                if ((_AirportInfoes == null))
                {
                    _AirportInfoes = base.CreateObjectSet<AirportInfo>("AirportInfoes");
                }
                return _AirportInfoes;
            }
        }
        private ObjectSet<AirportInfo> _AirportInfoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Flight> Flights
        {
            get
            {
                if ((_Flights == null))
                {
                    _Flights = base.CreateObjectSet<Flight>("Flights");
                }
                return _Flights;
            }
        }
        private ObjectSet<Flight> _Flights;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Member> Members
        {
            get
            {
                if ((_Members == null))
                {
                    _Members = base.CreateObjectSet<Member>("Members");
                }
                return _Members;
            }
        }
        private ObjectSet<Member> _Members;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TouristInfo> TouristInfoes
        {
            get
            {
                if ((_TouristInfoes == null))
                {
                    _TouristInfoes = base.CreateObjectSet<TouristInfo>("TouristInfoes");
                }
                return _TouristInfoes;
            }
        }
        private ObjectSet<TouristInfo> _TouristInfoes;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Aircraft EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAircraft(Aircraft aircraft)
        {
            base.AddObject("Aircraft", aircraft);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Aircrews EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAircrews(Aircrew aircrew)
        {
            base.AddObject("Aircrews", aircrew);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Airlines EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAirlines(Airline airline)
        {
            base.AddObject("Airlines", airline);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AirportInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAirportInfoes(AirportInfo airportInfo)
        {
            base.AddObject("AirportInfoes", airportInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Flights EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFlights(Flight flight)
        {
            base.AddObject("Flights", flight);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Members EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMembers(Member member)
        {
            base.AddObject("Members", member);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TouristInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTouristInfoes(TouristInfo touristInfo)
        {
            base.AddObject("TouristInfoes", touristInfo);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FlightsModel", Name="Aircraft")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Aircraft : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Aircraft object.
        /// </summary>
        /// <param name="aircraftID">Initial value of the AircraftID property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="firstDate">Initial value of the FirstDate property.</param>
        /// <param name="length">Initial value of the Length property.</param>
        /// <param name="height">Initial value of the Height property.</param>
        /// <param name="wingspan">Initial value of the Wingspan property.</param>
        /// <param name="diameter">Initial value of the Diameter property.</param>
        /// <param name="speed">Initial value of the Speed property.</param>
        /// <param name="manufacturer">Initial value of the Manufacturer property.</param>
        public static Aircraft CreateAircraft(global::System.Int32 aircraftID, global::System.String description, global::System.DateTime firstDate, global::System.Decimal length, global::System.Decimal height, global::System.Decimal wingspan, global::System.Decimal diameter, global::System.Decimal speed, global::System.String manufacturer)
        {
            Aircraft aircraft = new Aircraft();
            aircraft.AircraftID = aircraftID;
            aircraft.Description = description;
            aircraft.FirstDate = firstDate;
            aircraft.Length = length;
            aircraft.Height = height;
            aircraft.Wingspan = wingspan;
            aircraft.Diameter = diameter;
            aircraft.Speed = speed;
            aircraft.Manufacturer = manufacturer;
            return aircraft;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AircraftID
        {
            get
            {
                return _AircraftID;
            }
            set
            {
                if (_AircraftID != value)
                {
                    OnAircraftIDChanging(value);
                    ReportPropertyChanging("AircraftID");
                    _AircraftID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AircraftID");
                    OnAircraftIDChanged();
                }
            }
        }
        private global::System.Int32 _AircraftID;
        partial void OnAircraftIDChanging(global::System.Int32 value);
        partial void OnAircraftIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FirstDate
        {
            get
            {
                return _FirstDate;
            }
            set
            {
                OnFirstDateChanging(value);
                ReportPropertyChanging("FirstDate");
                _FirstDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FirstDate");
                OnFirstDateChanged();
            }
        }
        private global::System.DateTime _FirstDate;
        partial void OnFirstDateChanging(global::System.DateTime value);
        partial void OnFirstDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Length
        {
            get
            {
                return _Length;
            }
            set
            {
                OnLengthChanging(value);
                ReportPropertyChanging("Length");
                _Length = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Length");
                OnLengthChanged();
            }
        }
        private global::System.Decimal _Length;
        partial void OnLengthChanging(global::System.Decimal value);
        partial void OnLengthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Height
        {
            get
            {
                return _Height;
            }
            set
            {
                OnHeightChanging(value);
                ReportPropertyChanging("Height");
                _Height = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Height");
                OnHeightChanged();
            }
        }
        private global::System.Decimal _Height;
        partial void OnHeightChanging(global::System.Decimal value);
        partial void OnHeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Wingspan
        {
            get
            {
                return _Wingspan;
            }
            set
            {
                OnWingspanChanging(value);
                ReportPropertyChanging("Wingspan");
                _Wingspan = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Wingspan");
                OnWingspanChanged();
            }
        }
        private global::System.Decimal _Wingspan;
        partial void OnWingspanChanging(global::System.Decimal value);
        partial void OnWingspanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Diameter
        {
            get
            {
                return _Diameter;
            }
            set
            {
                OnDiameterChanging(value);
                ReportPropertyChanging("Diameter");
                _Diameter = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Diameter");
                OnDiameterChanged();
            }
        }
        private global::System.Decimal _Diameter;
        partial void OnDiameterChanging(global::System.Decimal value);
        partial void OnDiameterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Speed
        {
            get
            {
                return _Speed;
            }
            set
            {
                OnSpeedChanging(value);
                ReportPropertyChanging("Speed");
                _Speed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Speed");
                OnSpeedChanged();
            }
        }
        private global::System.Decimal _Speed;
        partial void OnSpeedChanging(global::System.Decimal value);
        partial void OnSpeedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Manufacturer
        {
            get
            {
                return _Manufacturer;
            }
            set
            {
                OnManufacturerChanging(value);
                ReportPropertyChanging("Manufacturer");
                _Manufacturer = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Manufacturer");
                OnManufacturerChanged();
            }
        }
        private global::System.String _Manufacturer;
        partial void OnManufacturerChanging(global::System.String value);
        partial void OnManufacturerChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FlightsModel", "FK_Flight_Aircraft", "Flight")]
        public EntityCollection<Flight> Flights
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Flight>("FlightsModel.FK_Flight_Aircraft", "Flight");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Flight>("FlightsModel.FK_Flight_Aircraft", "Flight", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FlightsModel", Name="Aircrew")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Aircrew : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Aircrew object.
        /// </summary>
        /// <param name="aircrewID">Initial value of the AircrewID property.</param>
        /// <param name="memberID">Initial value of the MemberID property.</param>
        public static Aircrew CreateAircrew(global::System.Int32 aircrewID, global::System.Int32 memberID)
        {
            Aircrew aircrew = new Aircrew();
            aircrew.AircrewID = aircrewID;
            aircrew.MemberID = memberID;
            return aircrew;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AircrewID
        {
            get
            {
                return _AircrewID;
            }
            set
            {
                if (_AircrewID != value)
                {
                    OnAircrewIDChanging(value);
                    ReportPropertyChanging("AircrewID");
                    _AircrewID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AircrewID");
                    OnAircrewIDChanged();
                }
            }
        }
        private global::System.Int32 _AircrewID;
        partial void OnAircrewIDChanging(global::System.Int32 value);
        partial void OnAircrewIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MemberID
        {
            get
            {
                return _MemberID;
            }
            set
            {
                if (_MemberID != value)
                {
                    OnMemberIDChanging(value);
                    ReportPropertyChanging("MemberID");
                    _MemberID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MemberID");
                    OnMemberIDChanged();
                }
            }
        }
        private global::System.Int32 _MemberID;
        partial void OnMemberIDChanging(global::System.Int32 value);
        partial void OnMemberIDChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FlightsModel", Name="Airline")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Airline : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Airline object.
        /// </summary>
        /// <param name="airlineID">Initial value of the AirlineID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="airlineCountry">Initial value of the AirlineCountry property.</param>
        /// <param name="phone">Initial value of the Phone property.</param>
        /// <param name="website">Initial value of the Website property.</param>
        /// <param name="onlineCheckIN">Initial value of the OnlineCheckIN property.</param>
        /// <param name="hotelBooking">Initial value of the HotelBooking property.</param>
        /// <param name="carRental">Initial value of the CarRental property.</param>
        public static Airline CreateAirline(global::System.Int32 airlineID, global::System.String name, global::System.String airlineCountry, global::System.String phone, global::System.String website, global::System.Int16 onlineCheckIN, global::System.Int16 hotelBooking, global::System.Int16 carRental)
        {
            Airline airline = new Airline();
            airline.AirlineID = airlineID;
            airline.Name = name;
            airline.AirlineCountry = airlineCountry;
            airline.Phone = phone;
            airline.Website = website;
            airline.OnlineCheckIN = onlineCheckIN;
            airline.HotelBooking = hotelBooking;
            airline.CarRental = carRental;
            return airline;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AirlineID
        {
            get
            {
                return _AirlineID;
            }
            set
            {
                if (_AirlineID != value)
                {
                    OnAirlineIDChanging(value);
                    ReportPropertyChanging("AirlineID");
                    _AirlineID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AirlineID");
                    OnAirlineIDChanged();
                }
            }
        }
        private global::System.Int32 _AirlineID;
        partial void OnAirlineIDChanging(global::System.Int32 value);
        partial void OnAirlineIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AirlineCountry
        {
            get
            {
                return _AirlineCountry;
            }
            set
            {
                OnAirlineCountryChanging(value);
                ReportPropertyChanging("AirlineCountry");
                _AirlineCountry = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AirlineCountry");
                OnAirlineCountryChanged();
            }
        }
        private global::System.String _AirlineCountry;
        partial void OnAirlineCountryChanging(global::System.String value);
        partial void OnAirlineCountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Website
        {
            get
            {
                return _Website;
            }
            set
            {
                OnWebsiteChanging(value);
                ReportPropertyChanging("Website");
                _Website = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Website");
                OnWebsiteChanged();
            }
        }
        private global::System.String _Website;
        partial void OnWebsiteChanging(global::System.String value);
        partial void OnWebsiteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 OnlineCheckIN
        {
            get
            {
                return _OnlineCheckIN;
            }
            set
            {
                OnOnlineCheckINChanging(value);
                ReportPropertyChanging("OnlineCheckIN");
                _OnlineCheckIN = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OnlineCheckIN");
                OnOnlineCheckINChanged();
            }
        }
        private global::System.Int16 _OnlineCheckIN;
        partial void OnOnlineCheckINChanging(global::System.Int16 value);
        partial void OnOnlineCheckINChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 HotelBooking
        {
            get
            {
                return _HotelBooking;
            }
            set
            {
                OnHotelBookingChanging(value);
                ReportPropertyChanging("HotelBooking");
                _HotelBooking = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HotelBooking");
                OnHotelBookingChanged();
            }
        }
        private global::System.Int16 _HotelBooking;
        partial void OnHotelBookingChanging(global::System.Int16 value);
        partial void OnHotelBookingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 CarRental
        {
            get
            {
                return _CarRental;
            }
            set
            {
                OnCarRentalChanging(value);
                ReportPropertyChanging("CarRental");
                _CarRental = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CarRental");
                OnCarRentalChanged();
            }
        }
        private global::System.Int16 _CarRental;
        partial void OnCarRentalChanging(global::System.Int16 value);
        partial void OnCarRentalChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FlightsModel", "FK_Flight_Airline", "Flight")]
        public EntityCollection<Flight> Flights
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Flight>("FlightsModel.FK_Flight_Airline", "Flight");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Flight>("FlightsModel.FK_Flight_Airline", "Flight", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FlightsModel", Name="AirportInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AirportInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AirportInfo object.
        /// </summary>
        /// <param name="airportID">Initial value of the AirportID property.</param>
        /// <param name="code">Initial value of the Code property.</param>
        /// <param name="airportPhone">Initial value of the AirportPhone property.</param>
        /// <param name="type">Initial value of the type property.</param>
        /// <param name="fax">Initial value of the fax property.</param>
        /// <param name="city">Initial value of the City property.</param>
        /// <param name="street">Initial value of the Street property.</param>
        /// <param name="postalcode">Initial value of the Postalcode property.</param>
        /// <param name="airportWebsite">Initial value of the AirportWebsite property.</param>
        public static AirportInfo CreateAirportInfo(global::System.Int32 airportID, global::System.String code, global::System.String airportPhone, global::System.Int16 type, global::System.Int16 fax, global::System.String city, global::System.String street, global::System.String postalcode, global::System.String airportWebsite)
        {
            AirportInfo airportInfo = new AirportInfo();
            airportInfo.AirportID = airportID;
            airportInfo.Code = code;
            airportInfo.AirportPhone = airportPhone;
            airportInfo.type = type;
            airportInfo.fax = fax;
            airportInfo.City = city;
            airportInfo.Street = street;
            airportInfo.Postalcode = postalcode;
            airportInfo.AirportWebsite = airportWebsite;
            return airportInfo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AirportID
        {
            get
            {
                return _AirportID;
            }
            set
            {
                if (_AirportID != value)
                {
                    OnAirportIDChanging(value);
                    ReportPropertyChanging("AirportID");
                    _AirportID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AirportID");
                    OnAirportIDChanged();
                }
            }
        }
        private global::System.Int32 _AirportID;
        partial void OnAirportIDChanging(global::System.Int32 value);
        partial void OnAirportIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AirportPhone
        {
            get
            {
                return _AirportPhone;
            }
            set
            {
                OnAirportPhoneChanging(value);
                ReportPropertyChanging("AirportPhone");
                _AirportPhone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AirportPhone");
                OnAirportPhoneChanged();
            }
        }
        private global::System.String _AirportPhone;
        partial void OnAirportPhoneChanging(global::System.String value);
        partial void OnAirportPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 type
        {
            get
            {
                return _type;
            }
            set
            {
                OntypeChanging(value);
                ReportPropertyChanging("type");
                _type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("type");
                OntypeChanged();
            }
        }
        private global::System.Int16 _type;
        partial void OntypeChanging(global::System.Int16 value);
        partial void OntypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 fax
        {
            get
            {
                return _fax;
            }
            set
            {
                OnfaxChanging(value);
                ReportPropertyChanging("fax");
                _fax = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fax");
                OnfaxChanged();
            }
        }
        private global::System.Int16 _fax;
        partial void OnfaxChanging(global::System.Int16 value);
        partial void OnfaxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Street
        {
            get
            {
                return _Street;
            }
            set
            {
                OnStreetChanging(value);
                ReportPropertyChanging("Street");
                _Street = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Street");
                OnStreetChanged();
            }
        }
        private global::System.String _Street;
        partial void OnStreetChanging(global::System.String value);
        partial void OnStreetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Postalcode
        {
            get
            {
                return _Postalcode;
            }
            set
            {
                OnPostalcodeChanging(value);
                ReportPropertyChanging("Postalcode");
                _Postalcode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Postalcode");
                OnPostalcodeChanged();
            }
        }
        private global::System.String _Postalcode;
        partial void OnPostalcodeChanging(global::System.String value);
        partial void OnPostalcodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AirportWebsite
        {
            get
            {
                return _AirportWebsite;
            }
            set
            {
                OnAirportWebsiteChanging(value);
                ReportPropertyChanging("AirportWebsite");
                _AirportWebsite = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AirportWebsite");
                OnAirportWebsiteChanged();
            }
        }
        private global::System.String _AirportWebsite;
        partial void OnAirportWebsiteChanging(global::System.String value);
        partial void OnAirportWebsiteChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FlightsModel", Name="Flight")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Flight : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Flight object.
        /// </summary>
        /// <param name="flightID">Initial value of the FlightID property.</param>
        /// <param name="airlineID">Initial value of the AirlineID property.</param>
        /// <param name="aircraftID">Initial value of the AircraftID property.</param>
        /// <param name="aircrewID">Initial value of the AircrewID property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="flightNumber">Initial value of the FlightNumber property.</param>
        /// <param name="depTime">Initial value of the DepTime property.</param>
        /// <param name="arrvTime">Initial value of the ArrvTime property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        /// <param name="groundOp">Initial value of the GroundOp property.</param>
        public static Flight CreateFlight(global::System.Int32 flightID, global::System.Int32 airlineID, global::System.Int32 aircraftID, global::System.Int32 aircrewID, global::System.DateTime date, global::System.String flightNumber, global::System.DateTime depTime, global::System.DateTime arrvTime, global::System.String status, global::System.String groundOp)
        {
            Flight flight = new Flight();
            flight.FlightID = flightID;
            flight.AirlineID = airlineID;
            flight.AircraftID = aircraftID;
            flight.AircrewID = aircrewID;
            flight.Date = date;
            flight.FlightNumber = flightNumber;
            flight.DepTime = depTime;
            flight.ArrvTime = arrvTime;
            flight.Status = status;
            flight.GroundOp = groundOp;
            return flight;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FlightID
        {
            get
            {
                return _FlightID;
            }
            set
            {
                if (_FlightID != value)
                {
                    OnFlightIDChanging(value);
                    ReportPropertyChanging("FlightID");
                    _FlightID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FlightID");
                    OnFlightIDChanged();
                }
            }
        }
        private global::System.Int32 _FlightID;
        partial void OnFlightIDChanging(global::System.Int32 value);
        partial void OnFlightIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AirlineID
        {
            get
            {
                return _AirlineID;
            }
            set
            {
                OnAirlineIDChanging(value);
                ReportPropertyChanging("AirlineID");
                _AirlineID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AirlineID");
                OnAirlineIDChanged();
            }
        }
        private global::System.Int32 _AirlineID;
        partial void OnAirlineIDChanging(global::System.Int32 value);
        partial void OnAirlineIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AircraftID
        {
            get
            {
                return _AircraftID;
            }
            set
            {
                OnAircraftIDChanging(value);
                ReportPropertyChanging("AircraftID");
                _AircraftID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AircraftID");
                OnAircraftIDChanged();
            }
        }
        private global::System.Int32 _AircraftID;
        partial void OnAircraftIDChanging(global::System.Int32 value);
        partial void OnAircraftIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AircrewID
        {
            get
            {
                return _AircrewID;
            }
            set
            {
                OnAircrewIDChanging(value);
                ReportPropertyChanging("AircrewID");
                _AircrewID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AircrewID");
                OnAircrewIDChanged();
            }
        }
        private global::System.Int32 _AircrewID;
        partial void OnAircrewIDChanging(global::System.Int32 value);
        partial void OnAircrewIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FlightNumber
        {
            get
            {
                return _FlightNumber;
            }
            set
            {
                OnFlightNumberChanging(value);
                ReportPropertyChanging("FlightNumber");
                _FlightNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FlightNumber");
                OnFlightNumberChanged();
            }
        }
        private global::System.String _FlightNumber;
        partial void OnFlightNumberChanging(global::System.String value);
        partial void OnFlightNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DepTime
        {
            get
            {
                return _DepTime;
            }
            set
            {
                OnDepTimeChanging(value);
                ReportPropertyChanging("DepTime");
                _DepTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DepTime");
                OnDepTimeChanged();
            }
        }
        private global::System.DateTime _DepTime;
        partial void OnDepTimeChanging(global::System.DateTime value);
        partial void OnDepTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ArrvTime
        {
            get
            {
                return _ArrvTime;
            }
            set
            {
                OnArrvTimeChanging(value);
                ReportPropertyChanging("ArrvTime");
                _ArrvTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ArrvTime");
                OnArrvTimeChanged();
            }
        }
        private global::System.DateTime _ArrvTime;
        partial void OnArrvTimeChanging(global::System.DateTime value);
        partial void OnArrvTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GroundOp
        {
            get
            {
                return _GroundOp;
            }
            set
            {
                OnGroundOpChanging(value);
                ReportPropertyChanging("GroundOp");
                _GroundOp = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("GroundOp");
                OnGroundOpChanged();
            }
        }
        private global::System.String _GroundOp;
        partial void OnGroundOpChanging(global::System.String value);
        partial void OnGroundOpChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FlightsModel", "FK_Flight_Aircraft", "Aircraft")]
        public Aircraft Aircraft
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Aircraft>("FlightsModel.FK_Flight_Aircraft", "Aircraft").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Aircraft>("FlightsModel.FK_Flight_Aircraft", "Aircraft").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Aircraft> AircraftReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Aircraft>("FlightsModel.FK_Flight_Aircraft", "Aircraft");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Aircraft>("FlightsModel.FK_Flight_Aircraft", "Aircraft", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FlightsModel", "FK_Flight_Airline", "Airline")]
        public Airline Airline
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Airline>("FlightsModel.FK_Flight_Airline", "Airline").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Airline>("FlightsModel.FK_Flight_Airline", "Airline").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Airline> AirlineReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Airline>("FlightsModel.FK_Flight_Airline", "Airline");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Airline>("FlightsModel.FK_Flight_Airline", "Airline", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FlightsModel", Name="Member")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Member : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Member object.
        /// </summary>
        /// <param name="memberID">Initial value of the MemberID property.</param>
        /// <param name="memberName">Initial value of the MemberName property.</param>
        /// <param name="position">Initial value of the Position property.</param>
        /// <param name="country">Initial value of the Country property.</param>
        /// <param name="age">Initial value of the Age property.</param>
        /// <param name="years">Initial value of the Years property.</param>
        public static Member CreateMember(global::System.Int32 memberID, global::System.String memberName, global::System.String position, global::System.String country, global::System.Int32 age, global::System.Int32 years)
        {
            Member member = new Member();
            member.MemberID = memberID;
            member.MemberName = memberName;
            member.Position = position;
            member.Country = country;
            member.Age = age;
            member.Years = years;
            return member;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MemberID
        {
            get
            {
                return _MemberID;
            }
            set
            {
                if (_MemberID != value)
                {
                    OnMemberIDChanging(value);
                    ReportPropertyChanging("MemberID");
                    _MemberID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MemberID");
                    OnMemberIDChanged();
                }
            }
        }
        private global::System.Int32 _MemberID;
        partial void OnMemberIDChanging(global::System.Int32 value);
        partial void OnMemberIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MemberName
        {
            get
            {
                return _MemberName;
            }
            set
            {
                OnMemberNameChanging(value);
                ReportPropertyChanging("MemberName");
                _MemberName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MemberName");
                OnMemberNameChanged();
            }
        }
        private global::System.String _MemberName;
        partial void OnMemberNameChanging(global::System.String value);
        partial void OnMemberNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Position
        {
            get
            {
                return _Position;
            }
            set
            {
                OnPositionChanging(value);
                ReportPropertyChanging("Position");
                _Position = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Position");
                OnPositionChanged();
            }
        }
        private global::System.String _Position;
        partial void OnPositionChanging(global::System.String value);
        partial void OnPositionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Country
        {
            get
            {
                return _Country;
            }
            set
            {
                OnCountryChanging(value);
                ReportPropertyChanging("Country");
                _Country = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Country");
                OnCountryChanged();
            }
        }
        private global::System.String _Country;
        partial void OnCountryChanging(global::System.String value);
        partial void OnCountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Age
        {
            get
            {
                return _Age;
            }
            set
            {
                OnAgeChanging(value);
                ReportPropertyChanging("Age");
                _Age = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Age");
                OnAgeChanged();
            }
        }
        private global::System.Int32 _Age;
        partial void OnAgeChanging(global::System.Int32 value);
        partial void OnAgeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Years
        {
            get
            {
                return _Years;
            }
            set
            {
                OnYearsChanging(value);
                ReportPropertyChanging("Years");
                _Years = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Years");
                OnYearsChanged();
            }
        }
        private global::System.Int32 _Years;
        partial void OnYearsChanging(global::System.Int32 value);
        partial void OnYearsChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FlightsModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FlightsModel", Name="TouristInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TouristInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TouristInfo object.
        /// </summary>
        /// <param name="infoID">Initial value of the InfoID property.</param>
        /// <param name="town">Initial value of the Town property.</param>
        /// <param name="timezone">Initial value of the Timezone property.</param>
        /// <param name="currency">Initial value of the Currency property.</param>
        /// <param name="averageTemperature">Initial value of the AverageTemperature property.</param>
        /// <param name="cityDescription">Initial value of the CityDescription property.</param>
        public static TouristInfo CreateTouristInfo(global::System.Int32 infoID, global::System.String town, global::System.String timezone, global::System.String currency, global::System.Decimal averageTemperature, global::System.String cityDescription)
        {
            TouristInfo touristInfo = new TouristInfo();
            touristInfo.InfoID = infoID;
            touristInfo.Town = town;
            touristInfo.Timezone = timezone;
            touristInfo.Currency = currency;
            touristInfo.AverageTemperature = averageTemperature;
            touristInfo.CityDescription = cityDescription;
            return touristInfo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 InfoID
        {
            get
            {
                return _InfoID;
            }
            set
            {
                if (_InfoID != value)
                {
                    OnInfoIDChanging(value);
                    ReportPropertyChanging("InfoID");
                    _InfoID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("InfoID");
                    OnInfoIDChanged();
                }
            }
        }
        private global::System.Int32 _InfoID;
        partial void OnInfoIDChanging(global::System.Int32 value);
        partial void OnInfoIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Town
        {
            get
            {
                return _Town;
            }
            set
            {
                OnTownChanging(value);
                ReportPropertyChanging("Town");
                _Town = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Town");
                OnTownChanged();
            }
        }
        private global::System.String _Town;
        partial void OnTownChanging(global::System.String value);
        partial void OnTownChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Timezone
        {
            get
            {
                return _Timezone;
            }
            set
            {
                OnTimezoneChanging(value);
                ReportPropertyChanging("Timezone");
                _Timezone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Timezone");
                OnTimezoneChanged();
            }
        }
        private global::System.String _Timezone;
        partial void OnTimezoneChanging(global::System.String value);
        partial void OnTimezoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Currency
        {
            get
            {
                return _Currency;
            }
            set
            {
                OnCurrencyChanging(value);
                ReportPropertyChanging("Currency");
                _Currency = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Currency");
                OnCurrencyChanged();
            }
        }
        private global::System.String _Currency;
        partial void OnCurrencyChanging(global::System.String value);
        partial void OnCurrencyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal AverageTemperature
        {
            get
            {
                return _AverageTemperature;
            }
            set
            {
                OnAverageTemperatureChanging(value);
                ReportPropertyChanging("AverageTemperature");
                _AverageTemperature = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AverageTemperature");
                OnAverageTemperatureChanged();
            }
        }
        private global::System.Decimal _AverageTemperature;
        partial void OnAverageTemperatureChanging(global::System.Decimal value);
        partial void OnAverageTemperatureChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CityDescription
        {
            get
            {
                return _CityDescription;
            }
            set
            {
                OnCityDescriptionChanging(value);
                ReportPropertyChanging("CityDescription");
                _CityDescription = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CityDescription");
                OnCityDescriptionChanged();
            }
        }
        private global::System.String _CityDescription;
        partial void OnCityDescriptionChanging(global::System.String value);
        partial void OnCityDescriptionChanged();

        #endregion

    
    }

    #endregion

    
}
